apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag.fullname" . }}-postgres
  labels:
    {{- include "rag.componentLabels" (merge (dict "component" "postgres") (deepCopy .)) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "rag.componentSelector" (dict "root" . "component" "postgres") | nindent 4 }}
